/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JournalsRouteImport } from './routes/journals'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalSlugIndexRouteImport } from './routes/journal.$slug.index'
import { Route as JournalSlugSectionRouteImport } from './routes/journal.$slug.$section'
import { Route as JournalSlugArticleIdRouteImport } from './routes/journal.$slug.article.$id'

const JournalsRoute = JournalsRouteImport.update({
  id: '/journals',
  path: '/journals',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugIndexRoute = JournalSlugIndexRouteImport.update({
  id: '/journal/$slug/',
  path: '/journal/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugSectionRoute = JournalSlugSectionRouteImport.update({
  id: '/journal/$slug/$section',
  path: '/journal/$slug/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugArticleIdRoute = JournalSlugArticleIdRouteImport.update({
  id: '/journal/$slug/article/$id',
  path: '/journal/$slug/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/journals': typeof JournalsRoute
  '/journal/$slug/$section': typeof JournalSlugSectionRoute
  '/journal/$slug/': typeof JournalSlugIndexRoute
  '/journal/$slug/article/$id': typeof JournalSlugArticleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/journals': typeof JournalsRoute
  '/journal/$slug/$section': typeof JournalSlugSectionRoute
  '/journal/$slug': typeof JournalSlugIndexRoute
  '/journal/$slug/article/$id': typeof JournalSlugArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/journals': typeof JournalsRoute
  '/journal/$slug/$section': typeof JournalSlugSectionRoute
  '/journal/$slug/': typeof JournalSlugIndexRoute
  '/journal/$slug/article/$id': typeof JournalSlugArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/journals'
    | '/journal/$slug/$section'
    | '/journal/$slug/'
    | '/journal/$slug/article/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/journals'
    | '/journal/$slug/$section'
    | '/journal/$slug'
    | '/journal/$slug/article/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/journals'
    | '/journal/$slug/$section'
    | '/journal/$slug/'
    | '/journal/$slug/article/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  JournalsRoute: typeof JournalsRoute
  JournalSlugSectionRoute: typeof JournalSlugSectionRoute
  JournalSlugIndexRoute: typeof JournalSlugIndexRoute
  JournalSlugArticleIdRoute: typeof JournalSlugArticleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/journals': {
      id: '/journals'
      path: '/journals'
      fullPath: '/journals'
      preLoaderRoute: typeof JournalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug/': {
      id: '/journal/$slug/'
      path: '/journal/$slug'
      fullPath: '/journal/$slug/'
      preLoaderRoute: typeof JournalSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug/$section': {
      id: '/journal/$slug/$section'
      path: '/journal/$slug/$section'
      fullPath: '/journal/$slug/$section'
      preLoaderRoute: typeof JournalSlugSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug/article/$id': {
      id: '/journal/$slug/article/$id'
      path: '/journal/$slug/article/$id'
      fullPath: '/journal/$slug/article/$id'
      preLoaderRoute: typeof JournalSlugArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  JournalsRoute: JournalsRoute,
  JournalSlugSectionRoute: JournalSlugSectionRoute,
  JournalSlugIndexRoute: JournalSlugIndexRoute,
  JournalSlugArticleIdRoute: JournalSlugArticleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
